name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore yoremio.sln

      - name: Build
        run: dotnet build yoremio.sln --configuration Release --no-restore

      - name: Test runner
        run: dotnet run --project Tests/Tests.csproj --configuration Release --no-build
